<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Utilisateur;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function insertUserFull($nom, $prenom, $classeOuFonction, $role, $mail, $tel, $slackName, $actif, $fkStatus){

		$user = new Utilisateur();
		$user->setNom($nom);
		$user->setPrenom($prenom);
		$user->setClasseOuFonction($classeOuFonction);
		$user->setRole($role);
		$user->setMail($mail);
		$user->setTel($tel);
		$user->setNomSlack($slackName);
		$user->setNomSlack($slackName);
		$user->setActif($actif);
		$user->setCdpProjet($fkProjet)
		$user->setIdStatuts($fkStatus);
		$em = $this->getDoctrine()->getManager();
	    $em->persist($product);
	    $em->flush();
	    
	}

	
}
